/* eslint-disable @typescript-eslint/no-unused-vars */

import Phaser from "phaser";

import {AudioManager} from "../components/audioManager";
import {CreaParoleAssetConf} from "../shared/config/asset-conf.const";

import {Game} from "./game";

const assetConf = CreaParoleAssetConf; //* Generalizzazione

// DEFINIZIONE DEI SET DI GIOCO
const GAME_SETS = [
  {
    // SET 1 - Lettere: A, C, E, L, M, O, R, S
    letters: ["A", "C", "E", "L", "M", "O", "R", "S"],
    validWords: [
      "reclamo",
      "calmero",
      "mescola",
      "scolare",
      "morale",
      "calore",
      "calmo",
      "clero",
      "morsa",
      "corsa",
      "scale",
      "sacro",
      "oscar",
      "losca",
      "merlo",
      "arco",
      "acre",
      "core",
      "cero",
      "cera",
      "orma",
      "ramo",
      "rame",
      "elmo",
      "mela",
      "male",
      "sole",
      "sale",
      "sera",
      "rosa",
      "mora",
      "cola",
      "coma",
      "alce",
      "lame",
      "mare",
      "care",
      "amo",
      "ora",
      "eco",
      "acero",
      "more",
      "ore",
      "roma",
      "melo",
      "morse",
      "rose",
      "resa",
      "reso",
      "era",
      "amore",
      "calo",
      "mole",
      "caro",
      "care",
      "remo",
      "malore",
      "clamore",
      "scemo",
      "scema",
      "calme",
      "amore",
      "sole",
      "scemarlo",
      "scremalo",
      "clamore",
      "colmare",
      "cremosa",
      "esclamo",
      "mescola",
      "moresca",
      "reclamo",
      "scarole",
      "scolare",
      "solcare",
      "arcole",
      "calore",
      "camole",
      "carole",
      "celoma",
      "cerosa",
      "colare",
      "colera",
      "colmar",
      "comare",
      "corale",
      "crealo",
      "creola",
      "acero",
      "locare",
      "macero",
      "malore",
      "molare",
      "morale",
      "osarle",
      "racemo",
      "ramose",
      "recalo",
      "remalo",
      "saremo",
      "scaleo",
      "scalmo",
      "sclera",
      "screma",
      "scremo",
      "semola",
      "smarco",
      "smerla",
      "smerlo",
      "solare",
      "somale",
      "somare",
      "acero",
      "amore",
      "asole",
      "calme",
      "calmo",
      "carme",
      "carso",
      "clero",
      "coesa",
      "colma",
      "colme",
      "colse",
      "corea",
      "corsa",
      "corse",
      "crema",
      "croma",
      "erosa",
      "esalo",
      "lasco",
      "laser",
      "lesmo",
      "losca",
      "macro",
      "marce",
      "merla",
      "merlo",
      "mores",
      "morsa",
      "morse",
      "mosca",
      "mosce",
      "orale",
      "osare",
      "rosea",
      "sacre",
      "sacro",
      "salme",
      "salmo",
      "scale",
      "scalo",
      "scema",
      "scemo",
      "scola",
      "solca",
      "acme",
      "acre",
      "acro",
      "alce",
      "ales",
      "almo",
      "aloe",
      "arco",
      "armo",
      "arse",
      "arso",
      "asce",
      "cale",
      "calo",
      "caos",
      "care",
      "caro",
      "case",
      "caso",
      "cela",
      "celo",
      "cera",
      "cero",
      "cola",
      "coma",
      "come",
      "cosa",
      "cose",
      "crea",
      "creo",
      "elmo",
      "elsa",
      "erma",
      "ermo",
      "eros",
      "esca",
      "esco",
      "lame",
      "laos",
      "lesa",
      "leso",
      "male",
      "mare",
      "maso",
      "mela",
      "melo",
      "mera",
      "mero",
      "mola",
      "mole",
      "mora",
      "more",
      "ocra",
      "ocre",
      "orca",
      "orla",
      "orma",
      "orme",
      "orsa",
      "orse",
      "rame",
      "ramo",
      "rase",
      "raso",
      "reca",
      "reco",
      "rema",
      "remo",
      "resa",
      "reso",
      "roma",
      "rosa",
      "rose",
      "sale",
      "sera",
      "sola",
      "sole",
      "soma",
      "ace",
      "amo",
      "eco",
      "era",
      "ero",
      "oca",
      "ora",
      "ore",
      "osa",
      "ram",
      "rea",
      "reo",
      "rom",
    ],
  },
  {
    // SET 2 - Lettere: B, I, A, N, C, O, R, E
    letters: ["B", "I", "N", "O", "E", "A", "R", "C"],
    validWords: [
      "ancora",
      "banco",
      "biancore",
      "bianco",
      "coreani",
      "erba",
      "baroni",
      "reni",
      "cabine",
      "canore",
      "nera",
      "carino",
      "cobra",
      "carine",
      "rancio",
      "bacino",
      "banca",
      "brace",
      "carne",
      "corna",
      "bacio",
      "barca",
      "canoe",
      "ciano",
      "acino",
      "barone",
      "brani",
      "corni",
      "arco",
      "cane",
      "caro",
      "cena",
      "nero",
      "nera",
      "neri",
      "roba",
      "beni",
      "boia",
      "orca",
      "inca",
      "boa",
      "neo",
      "era",
      "ore",
      "ora",
      "ancore",
      "bacio",
      "brano",
      "cani",
      "nei",
      "coni",
      "baci",
      "biancore",
      "arcione",
      "bacione",
      "barcone",
      "barconi",
      "barione",
      "baronie",
      "bonarie",
      "bracine",
      "bracino",
      "carbone",
      "carboni",
      "cibarne",
      "cinabro",
      "coniare",
      "coreani",
      "ebraico",
      "ocarine",
      "acerbi",
      "acerbo",
      "acerno",
      "aerino",
      "aerobi",
      "airone",
      "ancore",
      "areico",
      "bacino",
      "bareni",
      "bareno",
      "barico",
      "barone",
      "baroni",
      "bearci",
      "bercio",
      "bianco",
      "binare",
      "boarie",
      "bonari",
      "borace",
      "borica",
      "branco",
      "bronci",
      "cabine",
      "canore",
      "canori",
      "careno",
      "carine",
      "carino",
      "carnei",
      "carneo",
      "cenobi",
      "cerano",
      "cerino",
      "cernia",
      "ceroni",
      "cibano",
      "cibare",
      "cornea",
      "cornei",
      "cranio",
      "creano",
      "creino",
      "erbaio",
      "eroica",
      "eroina",
      "iberna",
      "iberno",
      "inarco",
      "narice",
      "norcia",
      "oceani",
      "orbace",
      "orbaci",
      "orcina",
      "rabico",
      "rancio",
      "recano",
      "renaio",
      "ribeca",
      "aceri",
      "acero",
      "acino",
      "anice",
      "areni",
      "areno",
      "arino",
      "arnie",
      "bacio",
      "bacon",
      "banco",
      "barco",
      "bario",
      "beano",
      "beona",
      "beoni",
      "berci",
      "berna",
      "bieca",
      "bieco",
      "boari",
      "boera",
      "boeri",
      "borea",
      "boria",
      "brace",
      "braci",
      "brani",
      "brano",
      "brina",
      "caino",
      "cairo",
      "canoe",
      "carie",
      "carne",
      "carni",
      "cenai",
      "cerio",
      "ciane",
      "ciano",
      "coane",
      "cobra",
      "conia",
      "corba",
      "corbe",
      "corna",
      "corni",
      "crani",
      "creai",
      "crine",
      "ebani",
      "ebano",
      "erano",
      "erbai",
      "erbio",
      "ernia",
      "icaro",
      "icona",
      "icone",
      "icore",
      "inaco",
      "nerbo",
      "noria",
      "obice",
      "oncia",
      "oneri",
      "onice",
      "orbai",
      "raion",
      "ranco",
      "recai",
      "renai",
      "renio",
      "rione",
      "roani",
      "acne",
      "acre",
      "acri",
      "acro",
      "arco",
      "arie",
      "arno",
      "baci",
      "baco",
      "baie",
      "baio",
      "bare",
      "bari",
      "baro",
      "beni",
      "bica",
      "bine",
      "bino",
      "biro",
      "boia",
      "bora",
      "brio",
      "caio",
      "cane",
      "cani",
      "care",
      "cari",
      "caro",
      "cebo",
      "cena",
      "ceni",
      "ceno",
      "cera",
      "ceri",
      "cero",
      "ciao",
      "ciba",
      "cibo",
      "cina",
      "coni",
      "cori",
      "crea",
      "crei",
      "creo",
      "eoni",
      "erba",
      "erbi",
      "eroi",
      "iena",
      "inca",
      "ione",
      "iran",
      "nari",
      "nera",
      "neri",
      "nero",
      "noce",
      "noci",
      "noia",
      "noie",
      "noir",
      "ocra",
      "once",
      "orba",
      "orbe",
      "orbi",
      "orca",
      "orci",
      "orna",
      "rane",
      "reca",
      "reco",
      "rena",
      "reni",
      "reno",
      "roba",
      "robe",
      "ace",
      "aie",
      "ani",
      "ano",
      "are",
      "ari",
      "aro",
      "bar",
      "bei",
      "ben",
      "boa",
      "boe",
      "cio",
      "coi",
      "con",
      "eco",
      "era",
      "eri",
      "ero",
      "ira",
      "ire",
      "nei",
      "neo",
      "noi",
      "oca",
      "ora",
      "ore",
      "ori",
      "rai",
      "rea",
      "rei",
      "reo",
      "rio",
      "rna",
    ],
  },
  {
    // SET 3 - Lettere: P, A, R, O, L, E, S, I
    letters: ["P", "A", "O", "S", "L", "R", "E", "I"],
    validWords: [
      "esplora",
      "isola",
      "parlesi",
      "parolie",
      "pelosi",
      "polari",
      "lesi",
      "leso",
      "pile",
      "separo",
      "solari",
      "spoiler",
      "spirale",
      "lepori",
      "perla",
      "priola",
      "rosalie",
      "parole",
      "perso",
      "isola",
      "leprosa",
      "polari",
      "sparo",
      "aspro",
      "lepra",
      "spola",
      "presa",
      "presa",
      "spera",
      "pari",
      "riso",
      "sola",
      "sole",
      "pera",
      "sera",
      "lira",
      "reso",
      "pose",
      "rosa",
      "arso",
      "ape",
      "ora",
      "pia",
      "posa",
      "lepri",
      "pila",
      "espiarlo",
      "espiralo",
      "esplorai",
      "pisolare",
      "resipola",
      "ripesalo",
      "riposale",
      "alserio",
      "espialo",
      "esplora",
      "esplori",
      "esporla",
      "esporli",
      "isolare",
      "operali",
      "operasi",
      "parelio",
      "pelarsi",
      "pesarli",
      "pesarlo",
      "porsela",
      "porseli",
      "posarle",
      "poserai",
      "posarli",
      "presalo",
      "presola",
      "presoli",
      "relapsi",
      "relapso",
      "saperli",
      "saperlo",
      "serialo",
      "serpaio",
      "soleari",
      "solerai",
      "sopirla",
      "sopirle",
      "sperali",
      "speralo",
      "spiarle",
      "spiarlo",
      "spirale",
      "spiralo",
      "spoiler",
      "airole",
      "aliseo",
      "apersi",
      "aporie",
      "apresi",
      "aprile",
      "aprilo",
      "ariose",
      "arpesi",
      "arsoli",
      "aspiro",
      "eloisa",
      "espira",
      "espiro",
      "oleari",
      "oliare",
      "oliera",
      "operai",
      "orlasi",
      "osarle",
      "osarli",
      "oserai",
      "palesi",
      "paleso",
      "pareli",
      "paresi",
      "parole",
      "pelasi",
      "pelosa",
      "pelosi",
      "persia",
      "pesali",
      "pesalo",
      "pesaro",
      "pilare",
      "pilosa",
      "pilose",
      "pirola",
      "pisola",
      "plesio",
      "poesia",
      "polare",
      "polari",
      "polesi",
      "posale",
      "posali",
      "posare",
      "rapesi",
      "rapile",
      "rapilo",
      "relais",
      "resola",
      "resoli",
      "ripesa",
      "ripeso",
      "riposa",
      "ripose",
      "risale",
      "risalo",
      "risape",
      "risapo",
      "risola",
      "rosale",
      "roseli",
      "salire",
      "saperi",
      "sapile",
      "sapilo",
      "sapore",
      "sapori",
      "saprei",
      "sepali",
      "sepalo",
      "separi",
      "separo",
      "seprio",
      "serali",
      "serial",
      "serpai",
      "solare",
      "solari",
      "sopila",
      "sopile",
      "sopire",
      "sparli",
      "sparlo",
      "spelai",
      "sperai",
      "sperla",
      "sperli",
      "sperlo",
      "spiale",
      "spialo",
      "spiare",
      "alesi",
      "aleso",
      "alose",
      "apiro",
      "arpie",
      "asilo",
      "asole",
      "aspre",
      "aspri",
      "aspro",
      "erosa",
      "erosi",
      "esali",
      "esalo",
      "esipo",
      "espia",
      "espio",
      "ilare",
      "irosa",
      "irose",
      "isola",
      "isole",
      "lapis",
      "lario",
      "laser",
      "lepri",
      "loira",
      "opale",
      "opali",
      "opera",
      "operi",
      "opsia",
      "orale",
      "orali",
      "orlai",
      "osale",
      "osali",
      "osare",
      "paesi",
      "palei",
      "paleo",
      "palio",
      "paoli",
      "parei",
      "pareo",
      "parie",
      "pario",
      "parli",
      "parlo",
      "parse",
      "parsi",
      "parso",
      "pelai",
      "perla",
      "persa",
      "persi",
      "perso",
      "pesai",
      "piera",
      "piero",
      "pileo",
      "pirla",
      "ploia",
      "polis",
      "polsi",
      "porla",
      "porle",
      "porli",
      "porse",
      "porsi",
      "posai",
      "praie",
      "presa",
      "presi",
      "preso",
      "prole",
      "proli",
      "prosa",
      "prose",
      "rasoi",
      "raspe",
      "raspi",
      "raspo",
      "reali",
      "rosai",
      "rosea",
      "rosei",
      "rospi",
      "salpe",
      "salpi",
      "salpo",
      "sapei",
      "sarei",
      "seria",
      "serio",
      "serpa",
      "serpi",
      "siero",
      "solai",
      "solea",
      "solei",
      "sopra",
      "spaio",
      "spali",
      "spalo",
      "spari",
      "sparo",
      "spela",
      "speli",
      "spelo",
      "spera",
      "speri",
      "spero",
      "spila",
      "spilo",
      "spira",
      "spire",
      "spiro",
      "spola",
      "spole",
      "spora",
      "spore",
      "aeri",
      "aloe",
      "alpi",
      "apre",
      "apri",
      "apro",
      "arie",
      "arpe",
      "arse",
      "arsi",
      "arso",
      "aspi",
      "aspo",
      "elia",
      "elio",
      "elsa",
      "epos",
      "eroi",
      "eros",
      "espi",
      "ialo",
      "ileo",
      "iseo",
      "laos",
      "lare",
      "lari",
      "lesa",
      "lesi",
      "leso",
      "lira",
      "lire",
      "liro",
      "lisa",
      "lise",
      "liso",
      "loia",
      "loie",
      "oasi",
      "olei",
      "olia",
      "opia",
      "orla",
      "orli",
      "orsa",
      "orse",
      "orsi",
      "osai",
      "paio",
      "pale",
      "pali",
      "palo",
      "pare",
      "pari",
      "paro",
      "peli",
      "pelo",
      "pera",
      "peri",
      "pero",
      "pesa",
      "pesi",
      "peso",
      "pila",
      "pile",
      "pilo",
      "pira",
      "pire",
      "piro",
      "pisa",
      "pois",
      "pola",
      "poli",
      "pori",
      "posa",
      "pose",
      "posi",
      "raie",
      "rape",
      "rapi",
      "rapo",
      "rase",
      "rasi",
      "raso",
      "real",
      "resa",
      "resi",
      "reso",
      "ripa",
      "ripe",
      "risa",
      "riso",
      "rosa",
      "rose",
      "saio",
      "sale",
      "sali",
      "sera",
      "seri",
      "silo",
      "sire",
      "slip",
      "soap",
      "soia",
      "sola",
      "sole",
      "soli",
      "spia",
      "spie",
      "spio",
      "ali",
      "ape",
      "api",
      "asl",
      "era",
      "eri",
      "ero",
      "ira",
      "iso",
      "lei",
      "oli",
      "ora",
      "ore",
      "ori",
      "osa",
      "osi",
      "pia",
      "pil",
      "pio",
      "poi",
      "rai",
      "reo",
      "rio",
      "sai",
      "sei",
      "sia",
      "sir",
      "spa",
    ],
  },
  {
    // SET 4 - Lettere: G, I, O, C, A, R, E, T
    letters: ["G", "O", "C", "A", "T", "I", "R", "E"],
    validWords: [
      "erotica",
      "giace",
      "tragico",
      "giro",
      "georgica",
      "reti",
      "torcia",
      "giocare",
      "regina",
      "girato",
      "recita",
      "gita",
      "gira",
      "carte",
      "riga",
      "orge",
      "arto",
      "rate",
      "ego",
      "oca",
      "era",
      "ira",
      "tre",
      "teoria",
      "gare",
      "tergi",
      "arti",
      "ora",
      "ore",
      "gioca",
      "eroi",
      "cogitare",
      "rogateci",
      "cairote",
      "erogaci",
      "erogati",
      "erotica",
      "giocare",
      "giocate",
      "grecati",
      "grecato",
      "reagito",
      "roteaci",
      "teorica",
      "toreaci",
      "tragico",
      "areico",
      "artico",
      "atroce",
      "atroci",
      "carote",
      "caroti",
      "cerati",
      "cerato",
      "citare",
      "coarti",
      "cogita",
      "corate",
      "cortei",
      "creati",
      "creato",
      "croate",
      "croati",
      "egioca",
      "erogai",
      "eroica",
      "geraci",
      "gerico",
      "getico",
      "girate",
      "girato",
      "gotica",
      "grecai",
      "grecia",
      "ortica",
      "otarie",
      "recati",
      "recato",
      "recita",
      "recito",
      "retica",
      "retico",
      "rigate",
      "rigato",
      "rogaci",
      "rogate",
      "rogati",
      "rogita",
      "rotaie",
      "roteai",
      "tagico",
      "teoria",
      "tirage",
      "torace",
      "toraci",
      "torcei",
      "torcia",
      "toreai",
      "torica",
      "tracie",
      "tracio",
      "triage",
      "troica",
      "aceri",
      "acero",
      "aceti",
      "aceto",
      "acori",
      "agire",
      "agite",
      "agito",
      "aorte",
      "atrio",
      "cairo",
      "cargo",
      "carie",
      "cario",
      "carte",
      "cerai",
      "cerio",
      "certa",
      "certi",
      "certo",
      "cetra",
      "corea",
      "corta",
      "corte",
      "corti",
      "creai",
      "creta",
      "egira",
      "erica",
      "eriga",
      "erigo",
      "eroga",
      "etica",
      "etico",
      "giace",
      "giaco",
      "giare",
      "gioca",
      "graie",
      "grate",
      "grati",
      "grato",
      "greca",
      "greci",
      "greco",
      "greta",
      "greti",
      "greto",
      "iatro",
      "icaro",
      "icore",
      "irate",
      "irato",
      "itaco",
      "itera",
      "itero",
      "orate",
      "orgia",
      "orgie",
      "otica",
      "ragie",
      "ratei",
      "rateo",
      "ratio",
      "reati",
      "reato",
      "recai",
      "regia",
      "regio",
      "rogai",
      "rotea",
      "rotei",
      "tacei",
      "targo",
      "terga",
      "tergi",
      "tergo",
      "terio",
      "tiare",
      "tigre",
      "tigro",
      "torca",
      "torce",
      "torci",
      "torei",
      "trace",
      "traci",
      "trago",
      "trico",
      "triga",
      "troia",
      "acre",
      "acri",
      "acro",
      "aeri",
      "aero",
      "agio",
      "agre",
      "agri",
      "agro",
      "aire",
      "arco",
      "arei",
      "areo",
      "argo",
      "arie",
      "arte",
      "arti",
      "arto",
      "atei",
      "ateo",
      "atri",
      "cago",
      "caio",
      "care",
      "cari",
      "caro",
      "cera",
      "ceri",
      "cero",
      "ceti",
      "ceto",
      "ciao",
      "ciro",
      "cita",
      "cito",
      "core",
      "cori",
      "cote",
      "crea",
      "crei",
      "creo",
      "crio",
      "egra",
      "egri",
      "egro",
      "erga",
      "ergi",
      "ergo",
      "eroi",
      "erta",
      "erti",
      "erto",
      "etio",
      "etra",
      "gaie",
      "gaio",
      "gare",
      "gato",
      "geco",
      "gera",
      "geti",
      "gioa",
      "gioe",
      "gira",
      "giro",
      "gita",
      "gite",
      "gora",
      "gore",
      "gota",
      "gote",
      "goti",
      "iato",
      "igor",
      "ioga",
      "iota",
      "irta",
      "irte",
      "irto",
      "iter",
      "ocra",
      "ocre",
      "orca",
      "orge",
      "orta",
      "orte",
      "orti",
      "otre",
      "rage",
      "raie",
      "rate",
      "rati",
      "rato",
      "reca",
      "reco",
      "regi",
      "reti",
      "rica",
      "riga",
      "rigo",
      "rita",
      "rito",
      "roca",
      "roga",
      "rota",
      "rote",
      "tace",
      "taci",
      "taco",
      "tago",
      "tare",
      "tari",
      "taro",
      "teca",
      "tega",
      "tera",
      "tira",
      "tiro",
      "toga",
      "tori",
      "trae",
      "trai",
      "trio",
      "ace",
      "agi",
      "ago",
      "art",
      "ate",
      "ati",
      "cio",
      "coi",
      "cri",
      "eco",
      "ego",
      "eia",
      "era",
      "eri",
      "ero",
      "eta",
      "geo",
      "ira",
      "oca",
      "ora",
      "ore",
      "ori",
      "rai",
      "rea",
      "rei",
      "reo",
      "rio",
      "tac",
      "tic",
      "tir",
      "tre",
    ],
  },
  {
    // SET 5 - Lettere: F, I, O, R, E, N, T, A
    letters: ["F", "I", "O", "N", "T", "E", "A", "R"],
    validWords: [
      "fortina",
      "inferta",
      "rafonte",
      "fortine",
      "fiorate",
      "tanfo",
      "rate",
      "fronte",
      "fonte",
      "fante",
      "finta",
      "rita",
      "finto",
      "forate",
      "franti",
      "infero",
      "ferita",
      "forati",
      "tonare",
      "frena",
      "fiato",
      "fiore",
      "forte",
      "fiona",
      "frate",
      "fiera",
      "torna",
      "torni",
      "ratio",
      "treno",
      "nero",
      "nera",
      "neri",
      "fine",
      "tira",
      "reti",
      "nota",
      "arte",
      "arto",
      "rane",
      "fate",
      "fifa",
      "ora",
      "era",
      "tre",
      "neo",
      "treni",
      "freno",
      "freni",
      "frane",
      "neri",
      "retina",
      "anfoteri",
      "foniatre",
      "forniate",
      "ronfiate",
      "tonferai",
      "aretino",
      "atrofie",
      "eforati",
      "erniato",
      "fiatone",
      "fintare",
      "fiorate",
      "foranei",
      "forante",
      "foranti",
      "foriate",
      "fornaie",
      "fornita",
      "fornite",
      "frantoi",
      "fratine",
      "fratino",
      "fratoni",
      "frenati",
      "frenato",
      "infarto",
      "inferta",
      "inferto",
      "iterano",
      "nefario",
      "neofita",
      "noterai",
      "noteria",
      "onerati",
      "orienta",
      "orinate",
      "orniate",
      "rateino",
      "reatino",
      "ronfate",
      "ronfati",
      "tenario",
      "tifarne",
      "tonerai",
      "tonfare",
      "torneai",
      "trefoni",
      "trionfa",
      "troiane",
      "tronfia",
      "tronfie",
      "aerino",
      "afonie",
      "airone",
      "anfore",
      "anitre",
      "anotie",
      "areino",
      "atonie",
      "entrai",
      "eroina",
      "farine",
      "farnie",
      "fatine",
      "fatino",
      "fenati",
      "fenato",
      "ferina",
      "ferino",
      "ferita",
      "ferito",
      "fetori",
      "finora",
      "fintar",
      "forane",
      "forate",
      "forati",
      "fornai",
      "frante",
      "franti",
      "franto",
      "frenai",
      "fronte",
      "fronti",
      "infera",
      "infero",
      "intera",
      "intero",
      "intrea",
      "nefari",
      "nitore",
      "notaie",
      "notare",
      "onerai",
      "orante",
      "oranti",
      "orfane",
      "orfani",
      "oriane",
      "ornate",
      "ornati",
      "otarie",
      "renaio",
      "renato",
      "retina",
      "retino",
      "rifate",
      "rinate",
      "rinato",
      "ritena",
      "riteno",
      "ronfai",
      "rotaie",
      "roteai",
      "tafone",
      "tafoni",
      "tarino",
      "tenari",
      "tenaro",
      "tenori",
      "teoria",
      "ternai",
      "tifane",
      "tifano",
      "tifare",
      "tifone",
      "tirane",
      "tirano",
      "tirone",
      "tonare",
      "tonari",
      "tonfai",
      "tonfar",
      "toreai",
      "tornai",
      "tornea",
      "tornei",
      "traine",
      "traino",
      "trofei",
      "trofia",
      "tronfi",
      "afnio",
      "afone",
      "afoni",
      "aneti",
      "aneto",
      "antri",
      "antro",
      "aorte",
      "areni",
      "areno",
      "arino",
      "arnie",
      "atone",
      "atoni",
      "atrio",
      "efori",
      "entra",
      "entri",
      "entro",
      "erano",
      "ernia",
      "etani",
      "etano",
      "etino",
      "etnia",
      "faine",
      "fante",
      "fanti",
      "farei",
      "farne",
      "farti",
      "feria",
      "fetra",
      "fiato",
      "fieno",
      "fiera",
      "fiero",
      "finta",
      "finte",
      "finto",
      "fiore",
      "fonia",
      "fonte",
      "fonti",
      "forai",
      "forni",
      "forte",
      "forti",
      "frane",
      "frani",
      "frano",
      "frate",
      "frati",
      "frena",
      "freni",
      "freno",
      "frina",
      "frine",
      "frino",
      "front",
      "iatro",
      "inera",
      "inero",
      "infra",
      "inter",
      "irate",
      "irato",
      "itera",
      "itero",
      "nafte",
      "natie",
      "natio",
      "nefro",
      "nitra",
      "nitre",
      "nitro",
      "noria",
      "norie",
      "notai",
      "notar",
      "ofite",
      "onera",
      "oneri",
      "orafe",
      "orafi",
      "orate",
      "orina",
      "orine",
      "ornai",
      "rafie",
      "raion",
      "ratei",
      "rateo",
      "ratio",
      "reati",
      "reato",
      "renai",
      "renio",
      "rione",
      "roane",
      "roani",
      "ronfa",
      "ronfi",
      "rotea",
      "rotei",
      "taine",
      "tanfi",
      "tanfo",
      "teano",
      "teina",
      "tenar",
      "tenia",
      "tenor",
      "terio",
      "terna",
      "terni",
      "terno",
      "tiare",
      "tifar",
      "tonai",
      "tonar",
      "toner",
      "tonfa",
      "tonfi",
      "tonia",
      "torea",
      "torei",
      "torna",
      "torne",
      "torni",
      "trane",
      "treni",
      "treno",
      "trina",
      "trine",
      "trino",
      "trofi",
      "troia",
      "troie",
      "troni",
      "aeri",
      "aero",
      "afre",
      "afri",
      "afro",
      "afte",
      "aire",
      "anfo",
      "ante",
      "arei",
      "areo",
      "arie",
      "arno",
      "arte",
      "arti",
      "arto",
      "atei",
      "ateo",
      "atri",
      "enti",
      "eoni",
      "eroi",
      "etio",
      "etna",
      "fare",
      "fari",
      "faro",
      "fate",
      "fati",
      "fato",
      "feti",
      "feto",
      "fine",
      "fino",
      "fior",
      "font",
      "fora",
      "fori",
      "iena",
      "ione",
      "iran",
      "irta",
      "irte",
      "irto",
      "iter",
      "nate",
      "nati",
      "nato",
      "nera",
      "neri",
      "nero",
      "noia",
      "noie",
      "noir",
      "nota",
      "note",
      "noti",
      "orna",
      "orni",
      "orta",
      "orte",
      "orti",
      "rane",
      "rate",
      "rena",
      "reni",
      "reno",
      "reti",
      "rito",
      "rota",
      "tane",
      "tare",
      "tera",
      "tifa",
      "tifo",
      "tino",
      "tira",
      "tiro",
      "tori",
      "trae",
      "trai",
      "trio",
      "ano",
      "era",
      "eri",
      "ero",
      "eta",
      "fai",
      "fan",
      "ira",
      "ire",
      "nei",
      "neo",
      "net",
      "nit",
      "noi",
      "nor",
      "ora",
      "ore",
      "ori",
      "rai",
      "rea",
      "rei",
      "reo",
      "ria",
      "rie",
      "rin",
      "rio",
      "rna",
      "tao",
      "tea",
      "tir",
      "tra",
      "tre",
    ],
  },
  {
    // SET 6 - Lettere: V, E, N, D, I, T, A, O
    letters: ["V", "N", "D", "T", "I", "E", "A", "O"],
    validWords: [
      "deviato",
      "doni",
      "doti",
      "nativo",
      "nati",
      "vendita",
      "invade",
      "divano",
      "devota",
      "toni",
      "donavi",
      "devoti",
      "novita",
      "dativo",
      "vanto",
      "vento",
      "vendo",
      "vinta",
      "dote",
      "dito",
      "dita",
      "dente",
      "tendo",
      "tenda",
      "venti",
      "dato",
      "diva",
      "vado",
      "vino",
      "nave",
      "vita",
      "vite",
      "nota",
      "nido",
      "onda",
      "dato",
      "date",
      "ante",
      "dea",
      "dio",
      "diva",
      "divo",
      "vena",
      "neo",
      "via",
      "dona",
      "doni",
      "tane",
      "avendoti",
      "denotavi",
      "detonavi",
      "donatevi",
      "evitando",
      "vietando",
      "aditone",
      "avitone",
      "denotai",
      "detonai",
      "deviano",
      "deviato",
      "diventa",
      "divento",
      "doniate",
      "doventi",
      "doviate",
      "editano",
      "editavo",
      "endotia",
      "evitano",
      "odiante",
      "tediano",
      "tediavo",
      "tendovi",
      "tondavi",
      "vendita",
      "videota",
      "vietano",
      "adenti",
      "adonti",
      "aidone",
      "andito",
      "anotie",
      "atonie",
      "avendo",
      "aventi",
      "datevi",
      "datino",
      "dative",
      "dativo",
      "datone",
      "datovi",
      "denota",
      "denoti",
      "detona",
      "detoni",
      "devano",
      "devino",
      "devota",
      "devoti",
      "dionea",
      "divano",
      "divena",
      "diveno",
      "donate",
      "donati",
      "donavi",
      "dotane",
      "dotavi",
      "dovine",
      "endoti",
      "endovi",
      "ideano",
      "ideato",
      "ideavo",
      "ideona",
      "idonea",
      "invade",
      "invado",
      "iodate",
      "natevi",
      "native",
      "nativo",
      "natovi",
      "nevaio",
      "nevati",
      "nevato",
      "notaie",
      "notavi",
      "odiane",
      "odiate",
      "ondate",
      "tedino",
      "teodia",
      "todina",
      "todine",
      "tonavi",
      "tondai",
      "vadino",
      "vedano",
      "venati",
      "venato",
      "videto",
      "vinate",
      "vinato",
      "votane",
      "adite",
      "adito",
      "adivo",
      "adone",
      "adoni",
      "aneti",
      "aneto",
      "anodi",
      "atone",
      "atoni",
      "aveni",
      "avide",
      "avido",
      "avine",
      "avite",
      "avito",
      "daino",
      "dante",
      "danti",
      "denti",
      "devia",
      "devio",
      "diane",
      "diano",
      "diate",
      "dieta",
      "donai",
      "dotai",
      "dovei",
      "edita",
      "edito",
      "etani",
      "etano",
      "etino",
      "etnia",
      "evadi",
      "evado",
      "evita",
      "evito",
      "invea",
      "inveo",
      "ivano",
      "natie",
      "natio",
      "nevai",
      "nevio",
      "nievo",
      "nivea",
      "niveo",
      "notai",
      "ovaie",
      "ovate",
      "ovati",
      "ovina",
      "ovine",
      "taide",
      "taine",
      "teano",
      "tedia",
      "tedio",
      "teina",
      "tenda",
      "tendi",
      "tendo",
      "tenia",
      "tiade",
      "tonai",
      "tonda",
      "tonde",
      "tondi",
      "tonia",
      "vanti",
      "vanto",
      "venai",
      "venda",
      "vendi",
      "vendo",
      "venia",
      "venti",
      "vento",
      "viado",
      "video",
      "vieta",
      "vieto",
      "vinta",
      "vinte",
      "vinto",
      "vitae",
      "votai",
      "aden",
      "aedi",
      "aedo",
      "ande",
      "ante",
      "atei",
      "ateo",
      "avei",
      "avio",
      "dane",
      "date",
      "dati",
      "dato",
      "davi",
      "davo",
      "deva",
      "devi",
      "devo",
      "dian",
      "dina",
      "dine",
      "dino",
      "dita",
      "dite",
      "dito",
      "diva",
      "dive",
      "divo",
      "dona",
      "doni",
      "dota",
      "dote",
      "doti",
      "dova",
      "dove",
      "dovi",
      "endo",
      "enti",
      "eoni",
      "etio",
      "etna",
      "evia",
      "iato",
      "idea",
      "ideo",
      "iena",
      "indo",
      "inta",
      "ione",
      "iota",
      "nate",
      "nati",
      "nato",
      "nave",
      "navi",
      "neva",
      "nevi",
      "nevo",
      "nido",
      "nodi",
      "noia",
      "noie",
      "nota",
      "note",
      "noti",
      "nova",
      "nove",
      "odia",
      "onda",
      "onde",
      "onta",
      "onte",
      "ovai",
      "tane",
      "tani",
      "teda",
      "tedi",
      "tena",
      "teni",
      "teno",
      "tino",
      "todi",
      "tona",
      "toni",
      "vade",
      "vado",
      "vaie",
      "vaio",
      "vane",
      "vani",
      "vano",
      "vate",
      "vati",
      "veda",
      "vedi",
      "vedo",
      "veio",
      "vena",
      "veni",
      "veno",
      "veti",
      "veto",
      "vide",
      "vine",
      "vino",
      "vita",
      "vite",
      "vota",
      "voti",
      "ade",
      "ani",
      "ano",
      "ave",
      "dai",
      "dea",
      "dei",
      "dio",
      "dna",
      "don",
      "eta",
      "eva",
      "evo",
      "ida",
      "iva",
      "nei",
      "neo",
      "noi",
      "ove",
      "vai",
      "van",
      "via",
      "vie",
      "voi",
    ],
  },
  {
    // SET 7 - Lettere: S, P, E, R, A, N, Z, O
    letters: ["S", "E", "R", "N", "A", "Z", "O", "P"],
    validWords: [
      "persona",
      "sperano",
      "pero",
      "pera",
      "perno",
      "nero",
      "pare",
      "nera",
      "nero",
      "spero",
      "sprone",
      "posare",
      "sperano",
      "senza",
      "zeno",
      "sarno",
      "seno",
      "sopra",
      "sano",
      "sprone",
      "praseno",
      "senza",
      "spera",
      "presa",
      "sparo",
      "perno",
      "prona",
      "prone",
      "aspro",
      "sera",
      "zona",
      "zone",
      "naso",
      "rane",
      "pare",
      "pane",
      "pena",
      "rosa",
      "naso",
      "pose",
      "sono",
      "rape",
      "spa",
      "era",
      "neo",
      "pranzo",
      "reo",
      "posa",
      "spera",
      "persona",
      "ponzare",
      "posarne",
      "soprane",
      "sperano",
      "sperona",
      "arpone",
      "arseno",
      "orzane",
      "osarne",
      "panzer",
      "penosa",
      "pesano",
      "pesaro",
      "posane",
      "posare",
      "pranzo",
      "renosa",
      "sapone",
      "sapore",
      "separo",
      "sprona",
      "sprone",
      "areno",
      "aspre",
      "aspro",
      "azero",
      "erano",
      "erosa",
      "esano",
      "naspo",
      "onera",
      "opera",
      "osane",
      "osare",
      "ozena",
      "panse",
      "pareo",
      "parse",
      "parso",
      "penar",
      "pensa",
      "penso",
      "perno",
      "persa",
      "perso",
      "pesan",
      "ponza",
      "porne",
      "porse",
      "posar",
      "presa",
      "preso",
      "prona",
      "prone",
      "prosa",
      "prose",
      "raspe",
      "raspo",
      "renzo",
      "roane",
      "ronza",
      "rosea",
      "sarno",
      "senza",
      "serpa",
      "sopra",
      "spano",
      "spare",
      "sparo",
      "spera",
      "spero",
      "spora",
      "spore",
      "aero",
      "anse",
      "anso",
      "apre",
      "apro",
      "areo",
      "arno",
      "arpe",
      "arse",
      "arso",
      "napo",
      "naso",
      "nepa",
      "nera",
      "nero",
      "nora",
      "orna",
      "orsa",
      "orse",
      "orza",
      "orze",
      "osar",
      "pane",
      "pano",
      "pare",
      "paro",
      "pena",
      "peno",
      "pera",
      "pero",
      "pesa",
      "peso",
      "pone",
      "posa",
      "pose",
      "rane",
      "rape",
      "rapo",
      "rase",
      "raso",
      "rena",
      "reno",
      "resa",
      "reso",
      "rosa",
      "rose",
      "sane",
      "sano",
      "sape",
      "sapo",
      "sena",
      "seno",
      "sera",
      "soap",
      "sopa",
      "sope",
      "zane",
      "zare",
      "zeno",
      "zero",
      "zona",
      "zone",
      "ano",
      "ape",
      "are",
      "aro",
      "era",
      "ero",
      "neo",
      "ora",
      "ore",
      "osa",
      "rea",
      "reo",
      "rna",
      "zar",
      "zen",
    ],
  },
  {
    // SET 8 - Lettere: M, U, S, I, C, A, L, E
    letters: ["M", "C", "E", "S", "I", "A", "L", "U"],
    validWords: [
      "calmesi",
      "missile",
      "emulsica",
      "mesali",
      "muli",
      "salumi",
      "clausme",
      "malice",
      "mica",
      "simula",
      "musica",
      "calmi",
      "clima",
      "usami",
      "salmo",
      "scale",
      "scuola",
      "muse",
      "musa",
      "scia",
      "mais",
      "sale",
      "male",
      "mela",
      "alce",
      "lume",
      "luca",
      "mali",
      "sale",
      "sali",
      "musi",
      "ali",
      "cui",
      "sua",
      "mai",
      "usa",
      "calme",
      "lesi",
      "emula",
      "musicale",
      "uscimela",
      "emulaci",
      "emulasi",
      "esclami",
      "esulaci",
      "esulami",
      "esumaci",
      "esumali",
      "mescila",
      "miscela",
      "museali",
      "musical",
      "scemali",
      "usaceli",
      "usameli",
      "acuesi",
      "acuile",
      "aculei",
      "camuse",
      "camusi",
      "casule",
      "celami",
      "celasi",
      "cimale",
      "cimase",
      "clisma",
      "emulai",
      "esulai",
      "esumai",
      "macule",
      "maculi",
      "malesi",
      "melica",
      "musica",
      "salemi",
      "salice",
      "salume",
      "salumi",
      "scalmi",
      "scemai",
      "sciale",
      "sciame",
      "selcia",
      "sicula",
      "sicule",
      "silema",
      "simula",
      "smiela",
      "sucila",
      "uscila",
      "uscile",
      "acesi",
      "acume",
      "acumi",
      "alesi",
      "alice",
      "calie",
      "calme",
      "calmi",
      "caule",
      "cause",
      "causi",
      "celai",
      "celia",
      "cesia",
      "clima",
      "culmi",
      "elica",
      "elisa",
      "elusa",
      "elusi",
      "emaci",
      "email",
      "emica",
      "emula",
      "emuli",
      "esali",
      "esami",
      "esima",
      "esula",
      "esuli",
      "esuma",
      "esumi",
      "islam",
      "lamie",
      "lasci",
      "lisca",
      "lisce",
      "lucia",
      "luisa",
      "lumai",
      "lusca",
      "macis",
      "malie",
      "mesca",
      "mesci",
      "musei",
      "salme",
      "salmi",
      "scale",
      "scali",
      "scema",
      "scemi",
      "selci",
      "slami",
      "umica",
      "umile",
      "usaci",
      "usale",
      "usali",
      "usami",
      "uscia",
      "acme",
      "acmi",
      "acue",
      "acui",
      "alce",
      "alci",
      "ales",
      "alme",
      "almi",
      "asce",
      "asci",
      "asmi",
      "aule",
      "cale",
      "cali",
      "case",
      "casi",
      "cela",
      "celi",
      "cile",
      "cima",
      "cime",
      "elia",
      "elmi",
      "elsa",
      "esca",
      "esci",
      "lame",
      "lesa",
      "lesi",
      "lima",
      "lime",
      "lisa",
      "lise",
      "luca",
      "luce",
      "luci",
      "lume",
      "lumi",
      "mail",
      "mais",
      "male",
      "mali",
      "masi",
      "mela",
      "meli",
      "mesi",
      "mica",
      "mila",
      "misa",
      "mise",
      "mula",
      "mule",
      "muli",
      "musa",
      "muse",
      "musi",
      "sale",
      "sali",
      "sami",
      "saul",
      "scia",
      "scie",
      "semi",
      "seul",
      "siam",
      "sica",
      "sila",
      "slam",
      "slum",
      "sula",
      "sule",
      "usai",
      "usca",
      "usce",
      "usci",
      "ace",
      "aci",
      "acl",
      "aie",
      "ali",
      "ami",
      "asl",
      "lei",
      "lui",
      "mai",
      "mia",
      "mie",
      "sai",
      "sci",
      "sei",
      "sia",
      "sua",
      "sue",
      "usa",
      "use",
      "usi",
    ],
  },
];

export class GameManager extends Phaser.Scene {
  audioManager!: AudioManager;

  private gameWidth!: number;
  private gameHeight!: number;

  private marginTop = 200;
  private letterBlocks: Array<{
    block: Phaser.GameObjects.Image;
    letter: Phaser.GameObjects.Text;
    originalX: number;
    originalY: number;
    letterValue: string;
    isPlaced: boolean;
  }> = [];

  private placedLetters: Array<{
    block: Phaser.GameObjects.Image;
    letter: Phaser.GameObjects.Text;
    index: number;
  }> = [];

  private grid!: Phaser.GameObjects.Image;
  private mainContainer!: Phaser.GameObjects.Container;

  // Set di gioco corrente
  private currentGameSet!: {letters: string[]; validWords: string[]};

  // ARRAY DELLE PAROLE VALIDE
  private validWords: string[] = [];

  // CONTA PAROLE TROVATE
  private wordsFound: string[] = [];

  private computeLayoutDimensions() {
    this.gameWidth = this.sys.game.config.width as number;
    this.gameHeight = this.sys.game.config.height as number;
  }

  public canShoot: boolean = true;
  public isGameOver: boolean = false;
  private isCelebrating: boolean = false;

  gameScene!: Game;
  speedBall: number = 800;
  timeAddNewRow: number = 20000;

  constructor() {
    super({key: assetConf.scene.gameManager});
  }

  init(data: {gameScene?: Game}) {
    if (data.gameScene) {
      this.gameScene = data.gameScene;
    }

    // SELEZIONA UN SET CASUALE ALL'INIZIO DELLA PARTITA
    const randomIndex = Phaser.Math.Between(0, GAME_SETS.length - 1);

    this.currentGameSet = GAME_SETS[randomIndex];
    this.validWords = this.currentGameSet.validWords;

    console.log(`Set di gioco selezionato: ${randomIndex + 1}`);
    console.log(`Lettere disponibili: ${this.currentGameSet.letters.join(", ")}`);
  }

  create() {
    console.log("StartGame");
    this.computeLayoutDimensions();

    this.canShoot = true;
    this.isGameOver = false;
    this.wordsFound = []; // Reset delle parole trovate

    // CREA UN CONTENITORE INVISIBILE
    this.mainContainer = this.add.container(0, 0);

    // CREA GRID AL CENTRO DEL CONTAINER (usa coordinate 0,0 relative al container!)
    this.grid = this.add.image(0, 0, "grid");
    this.grid.setOrigin(0.5);

    const gridOffsetY = -50;

    this.grid.setPosition(0, gridOffsetY); // COORDINATE RELATIVE AL CONTAINER
    this.mainContainer.add(this.grid);

    // CREA GOMMA DA CANCELLARE IN BASSO A DESTRA DELLA GRID
    const deleteBtn = this.add.image(0, 0, "delete");

    deleteBtn.setOrigin(1, 1);
    deleteBtn.setScale(0.8);
    deleteBtn.setPosition(
      this.grid.x + this.grid.displayWidth / 2 - 50,
      this.grid.y + this.grid.displayHeight / 2 - 50,
    );
    deleteBtn.setInteractive({useHandCursor: true});
    deleteBtn.on("pointerdown", () => this.resetAllLetters());
    this.mainContainer.add(deleteBtn);

    // CREA 8 BLOCCHI SOTTO GRID CON LETTERE
    const blockSpacingX = 45;
    const blockSpacingY = 35;
    const blocksPerRiga = 4;
    const paddingGridBlocks = 150;

    const blocksStartY = this.grid.y + this.grid.displayHeight / 2 + paddingGridBlocks;

    // USA LE LETTERE DEL SET CORRENTE (invece di array fisso)
    const letters = this.currentGameSet.letters;

    this.letterBlocks = [];

    for (let i = 0; i < 8; i++) {
      const block = this.add.image(0, 0, "block");

      block.setOrigin(0.5);
      block.setScale(1.1); // BLOCCHI ESTERNI PIÙ GRANDI

      const row = Math.floor(i / blocksPerRiga);
      const col = i % blocksPerRiga;

      const totalWidth = blocksPerRiga * block.width + (blocksPerRiga - 1) * blockSpacingX;

      // CENTRA I BLOCCHI ORIZZONTALMENTE
      const blockX = -totalWidth / 2 + block.width / 2 + col * (block.width + blockSpacingX);
      const blockY = blocksStartY + row * (block.height + blockSpacingY);

      block.setPosition(blockX, blockY);
      this.mainContainer.add(block);

      // AGGIUNGI LA LETTERA BIANCA SOPRA IL BLOCCO
      const letter = this.add.text(blockX, blockY, letters[i], {
        fontFamily: "Arial",
        fontSize: "85px",
        color: "#ffffff",
        fontStyle: "bold",
      });

      letter.setOrigin(0.5);
      this.mainContainer.add(letter);

      // SALVA IN ARRAY INFORMAZIONI SUL BLOCCO E LETTERA
      this.letterBlocks.push({
        block,
        letter,
        originalX: blockX,
        originalY: blockY,
        letterValue: letters[i],
        isPlaced: false,
      });

      // RENDE IL BLOCCO TRASCINABILE
      this.setupDraggable(block, letter, i);
    }

    // SCALA MANUALMENTE IN BASE ALLE DIMENSIONI DELLO SCHERMO
    let scale = 1;

    // ABBASSA le dimensioni di riferimento per aumentare lo scale sui cellulari
    const scaleByWidth = this.gameWidth / 1200;
    const scaleByHeight = this.gameHeight / 800;

    // Usa il valore minore per assicurarti che tutto rimanga visibile
    scale = Math.min(scaleByWidth, scaleByHeight);

    // AUMENTA i limiti per permettere dimensioni maggiori
    scale = Math.max(0.7, Math.min(scale, 1.5)); // min 0.7, max 1.5

    // Aggiungi un moltiplicatore fisso per aumentare tutto
    scale = scale * 1; // aumenta del 10% tutte le dimensioni

    this.mainContainer.setScale(scale);

    // CENTRA IL CONTAINER NELLO SCHERMO
    this.mainContainer.x = this.gameWidth / 2;
    this.mainContainer.y = this.gameHeight / 2;
  }

  private setupDraggable(
    block: Phaser.GameObjects.Image,
    letter: Phaser.GameObjects.Text,
    index: number,
  ) {
    block.setInteractive({useHandCursor: true});
    this.input.setDraggable(block);

    let dragStartX = 0;
    let dragStartY = 0;
    let isDragging = false;
    const DRAG_THRESHOLD = 10;

    block.on("dragstart", (pointer: Phaser.Input.Pointer) => {
      dragStartX = pointer.x;
      dragStartY = pointer.y;
      isDragging = false;
    });

    block.on("drag", (pointer: Phaser.Input.Pointer, dragX: number, dragY: number) => {
      const distance = Phaser.Math.Distance.Between(dragStartX, dragStartY, pointer.x, pointer.y);

      if (!isDragging && distance > DRAG_THRESHOLD) {
        isDragging = true;

        // Porta in primo piano
        this.mainContainer.bringToTop(block);
        this.mainContainer.bringToTop(letter);
        block.setTint(0xaaaaaa);

        // Rimuovi dalla grid se era piazzata
        const blockData = this.letterBlocks[index];

        if (blockData.isPlaced) {
          this.placedLetters = this.placedLetters.filter((p) => p.index !== index);
          blockData.isPlaced = false;
        }
      }

      // Muovi il blocco solo se il drag è attivo
      if (isDragging) {
        block.setPosition(dragX, dragY);
        letter.setPosition(dragX, dragY);
      }
    });

    block.on("dragend", () => {
      const blockData = this.letterBlocks[index];

      // Se non abbiamo superato la soglia = è stato un CLICK, non un drag
      if (!isDragging) {
        // GESTIONE CLICK:
        if (!blockData.isPlaced) {
          // Se non è piazzato, sposta il blocco alla grid
          this.placeLetterOnGrid(blockData, index);
        } else {
          // Se è già piazzato, torna alla posizione originale
          this.returnToOriginalPosition(blockData);
          // Rimuovi dalla lista delle lettere piazzate
          this.placedLetters = this.placedLetters.filter((p) => p.index !== index);
          // Riposiziona le lettere rimanenti nella grid
          this.repositionGridLetters();
        }

        return;
      }

      // GESTIONE DRAG: è stato un vero trascinamento
      block.clearTint();

      // Verifica se il blocco è stato rilasciato sulla grid
      if (this.isOverGrid(block)) {
        this.placeLetterOnGrid(blockData, index);
      } else {
        // Torna alla posizione originale
        this.returnToOriginalPosition(blockData);
      }
    });
  }

  private isOverGrid(block: Phaser.GameObjects.Image): boolean {
    const blockBounds = block.getBounds();
    const gridBounds = this.grid.getBounds();

    return Phaser.Geom.Intersects.RectangleToRectangle(blockBounds, gridBounds);
  }

  private placeLetterOnGrid(
    blockData: {
      block: Phaser.GameObjects.Image;
      letter: Phaser.GameObjects.Text;
      originalX: number;
      originalY: number;
      letterValue: string;
      isPlaced: boolean;
    },
    index: number,
  ) {
    // Blocca durante la celebrazione
    if (this.isCelebrating) {
      this.returnToOriginalPosition(blockData);
      return;
    }

    // Rimuovi dalla posizione precedente se era già piazzata
    if (blockData.isPlaced) {
      this.placedLetters = this.placedLetters.filter((p) => p.index !== index);
    }

    // Aggiungi alla lista delle lettere piazzate
    this.placedLetters.push({
      block: blockData.block,
      letter: blockData.letter,
      index,
    });

    blockData.isPlaced = true;

    // Suono quando si piazza una lettera
    this.gameScene.audioManager.playAudio(assetConf.audio.error);

    // Riposiziona tutte le lettere nella grid
    this.repositionGridLetters();

    // Controlla se si è formata una parola valida
    this.checkForValidWord();
  }

  private repositionGridLetters() {
    const count = this.placedLetters.length;

    // Scala dinamica: più lettere più piccole
    const baseScale = 1.2;
    const minScale = 0.6;
    const scaleFactor = Math.max(minScale, baseScale - (count - 1) * 0.08);

    // Spaziatura dinamica in base alla scala
    const baseSpacing = 180;
    const letterSpacing = baseSpacing * scaleFactor;

    const totalWidth = (count - 1) * letterSpacing;
    const startX = -totalWidth / 2;

    this.placedLetters.forEach((placed, i) => {
      const targetX = startX + i * letterSpacing;
      const targetY = this.grid.y;

      this.tweens.add({
        targets: placed.block,
        x: targetX,
        y: targetY,
        scale: scaleFactor,
        duration: 200,
        ease: "Power2",
      });

      // Scala anche il font della lettera
      const fontSize = Math.round(85 * scaleFactor);

      this.tweens.add({
        targets: placed.letter,
        x: targetX,
        y: targetY,
        duration: 200,
        ease: "Power2",
        onUpdate: () => {
          placed.letter.setFontSize(fontSize);
        },
      });
    });
  }

  private returnToOriginalPosition(blockData: {
    block: Phaser.GameObjects.Image;
    letter: Phaser.GameObjects.Text;
    originalX: number;
    originalY: number;
    letterValue: string;
    isPlaced: boolean;
  }) {
    // Ferma eventuali tween in corso
    this.tweens.killTweensOf(blockData.block);
    this.tweens.killTweensOf(blockData.letter);

    // Ripristina immediatamente scala e font originali
    blockData.block.setScale(1.1);
    blockData.letter.setScale(1); // Reset scale del Text
    blockData.letter.setFontSize(85);

    this.tweens.add({
      targets: [blockData.block, blockData.letter],
      x: blockData.originalX,
      y: blockData.originalY,
      duration: 200,
      ease: "Power2",
    });

    blockData.isPlaced = false;
  }

  private resetAllLetters() {
    console.log("Reset tutte le lettere");

    // Suono quando si usa il deleteBtn
    //this.gameScene.audioManager.playAudio(assetConf.audio.error);

    // Resetta tutte le lettere alle posizioni originali
    this.letterBlocks.forEach((blockData) => {
      if (blockData.isPlaced) {
        this.returnToOriginalPosition(blockData);
      }
    });

    // Svuota l'array delle lettere piazzate
    this.placedLetters = [];
  }

  // Nuovo metodo per controllare se si è formata una parola valida
  private checkForValidWord() {
    // Costruisci la parola dalle lettere piazzate
    const currentWord = this.placedLetters
      .map((placed) => this.letterBlocks[placed.index].letterValue)
      .join("")
      .toLowerCase();

    // Controlla se la parola è nell'array delle parole valide
    if (this.validWords.includes(currentWord) && !this.wordsFound.includes(currentWord)) {
      // Parola trovata!
      this.wordsFound.push(currentWord);
      const wordNumber = this.wordsFound.length;

      console.log(`PAROLA ${wordNumber} TROVATA: ${currentWord.toUpperCase()}`);
      this.gameScene.uiManager.updateScore(1); // Aggiorna il punteggio di 1 punti

      // Qui puoi aggiungere effetti visivi o audio per celebrare la parola trovata
      this.celebrateWord(currentWord);

      // Controlla se sono state trovate 3 parole
      if (this.wordsFound.length >= 3) {
        console.log("3 PAROLE TROVATE! ATTIVAZIONE GAME OVER");
        this.isGameOver = true;
        this.checkGameOver();
      }
    }
  }

  // Metodo opzionale per celebrare la parola trovata
  private celebrateWord(word: string) {
    // Blocca l'aggiunta di nuove lettere durante la celebrazione
    this.isCelebrating = true;

    // Suono di successo quando si trova una parola
    this.gameScene.audioManager.playAudio(assetConf.audio.success);

    // IMPORTANTE: Salva una copia snapshot dell'array PRIMA di animare
    const lettersToAnimate = [...this.placedLetters];
    const totalLetters = lettersToAnimate.length;

    // IMPORTANTE: Ferma tutti i tween in corso sui blocchi (es. repositionGridLetters)
    // e posiziona subito le lettere nella posizione corretta della grid
    const baseScale = 1.2;
    const minScale = 0.6;
    const scaleFactor = Math.max(minScale, baseScale - (totalLetters - 1) * 0.065);
    const baseSpacing = 180;
    const letterSpacing = baseSpacing * scaleFactor;
    const totalWidth = (totalLetters - 1) * letterSpacing;
    const startX = -totalWidth / 2;

    lettersToAnimate.forEach((placed, i) => {
      this.tweens.killTweensOf(placed.block);
      this.tweens.killTweensOf(placed.letter);

      // Forza lo scale corretto per TUTTI i blocchi (l'ultimo potrebbe non aver finito il tween)
      placed.block.setScale(scaleFactor);
      const fontSize = Math.round(85 * scaleFactor);
      placed.letter.setFontSize(fontSize);

      // Posiziona immediatamente nella posizione corretta della grid
      const targetX = startX + i * letterSpacing;
      const targetY = this.grid.y;
      placed.block.setPosition(targetX, targetY);
      placed.letter.setPosition(targetX, targetY);
    });

    // Salva le posizioni e scale (ora tutti hanno lo stesso scaleFactor)
    const originalData = lettersToAnimate.map((placed) => ({
      block: placed.block,
      letter: placed.letter,
      originalX: placed.block.x,
      originalY: placed.block.y,
      originalScale: scaleFactor, // Usa scaleFactor, non block.scaleX
      originalDepth: placed.block.depth,
    }));

    const staggerDelay = 100; // Delay tra ogni lettera
    const zoomDuration = 300; // Durata zoom
    const returnDuration = 200; // Durata ritorno

    // Calcola tempo totale: ultimo delay + zoom + ritorno
    const totalAnimationTime = (totalLetters - 1) * staggerDelay + zoomDuration + returnDuration;

    // Anima le lettere in sequenza con effetto elegante
    lettersToAnimate.forEach((placed, i) => {
      const delay = i * staggerDelay;
      const block = placed.block;
      const letter = placed.letter;

      // Porta in primo piano durante l'animazione
      this.mainContainer.bringToTop(block);
      this.mainContainer.bringToTop(letter);
      block.setDepth(1000 + i);
      letter.setDepth(1001 + i);

      // Posizione nella grid
      const posX = originalData[i].originalX;
      const posY = originalData[i].originalY;
      const blockScale = originalData[i].originalScale;

      // Animazione blocco: zoom up poi ritorno
      this.tweens.add({
        targets: block,
        scale: blockScale * 1.5,
        y: posY - 50,
        duration: zoomDuration,
        ease: "Back.easeOut",
        delay: delay,
        onStart: () => {
          block.setTint(0xffff00);
        },
        onComplete: () => {
          this.tweens.add({
            targets: block,
            scale: blockScale,
            y: posY,
            duration: returnDuration,
            ease: "Power2.easeIn",
            onComplete: () => {
              block.clearTint();
              block.setDepth(originalData[i].originalDepth);
            },
          });
        },
      });

      // Animazione lettera: segue il blocco (solo movimento Y)
      this.tweens.add({
        targets: letter,
        y: posY - 50,
        duration: zoomDuration,
        ease: "Back.easeOut",
        delay: delay,
        onComplete: () => {
          this.tweens.add({
            targets: letter,
            y: posY,
            duration: returnDuration,
            ease: "Power2.easeIn",
            onComplete: () => {
              letter.setDepth(originalData[i].originalDepth);
            },
          });
        },
      });
    });

    // Aspetta che TUTTE le animazioni finiscano + 1 secondo, poi resetta
    this.time.delayedCall(totalAnimationTime + 1000, () => {
      // Reset DIRETTO dei blocchi salvati (non usare resetAllLetters che potrebbe avere stato diverso)
      lettersToAnimate.forEach((placed) => {
        const blockData = this.letterBlocks[placed.index];

        // Ferma tutti i tween
        this.tweens.killTweensOf(blockData.block);
        this.tweens.killTweensOf(blockData.letter);

        // Forza dimensioni originali
        blockData.block.setScale(1.1);
        blockData.letter.setScale(1);
        blockData.letter.setFontSize(85);

        // Anima ritorno alla posizione originale
        this.tweens.add({
          targets: [blockData.block, blockData.letter],
          x: blockData.originalX,
          y: blockData.originalY,
          duration: 200,
          ease: "Power2",
        });

        blockData.isPlaced = false;
      });

      this.placedLetters = [];

      // Riabilita l'aggiunta di lettere dopo la celebrazione
      this.isCelebrating = false;
    });
  }

  startAnimConfetti() {
    const config = this.sys.game.config as {width: number; height: number};

    const spriteLeft = this.add
      .sprite(0, config.height / 2, assetConf.spritesheet.confetti_left.key)
      .setOrigin(0, 0.5)
      .setDepth(15)
      .setScale(5)
      .setScrollFactor(0);

    this.anims.create({
      key: "animConfettiLeft",
      frames: this.anims.generateFrameNumbers(assetConf.spritesheet.confetti_left.key, {
        start: 0,
        end: 54,
      }),
      frameRate: 20,
    });

    spriteLeft.play("animConfettiLeft");

    const spriteRight = this.add
      .sprite(config.width, config.height / 2, assetConf.spritesheet.confetti_right.key)
      .setOrigin(1, 0.5)
      .setDepth(15)
      .setScale(5)
      .setScrollFactor(0);

    this.anims.create({
      key: "animConfettiRight",
      frames: this.anims.generateFrameNumbers(assetConf.spritesheet.confetti_right.key, {
        start: 0,
        end: 54,
      }),
      frameRate: 20,
    });

    spriteRight.play("animConfettiRight");
  }

  checkGameOver() {
    if (this.isGameOver) {
      console.log(`GAME OVER:`);
      this.canShoot = false;
      this.gameScene.gameOver();
    }
  }
}

//! BACKGROUND AL TIMEMANAGER E CLESSIDRA RIDOTTA, PIU' SCENARI DI PAROLE E LETTERE, ICONSCORE A SINISTRA IN ALTO
